export const COLORS = {
    "LOGIN_BUTTON_BLUE": '#2C63A1',
    "LOGIN_BACKGROUND": '#272727',
    "PRIMARY_BLUE": '#212E66',
    "NAVBAR_BACKGROUND_GREY": '#F8F8F8',
    "NAVBAR_BUTTON_HIGHLIGHTED": '#4292EC',
    "WHITE": '#FFFFFF', 
}